import { Item } from '../../shared/types/items.types';
import { User } from '../../shared/types/user.types';

export const testItems: Item[] = [
    { id: 1, primaryItemCategory: 'beer', secondaryItemCategory: 'pilsner', name: 'Carlsberg Pilsner', averagePrice: 15, currentStock: 10, totalStockValue: 1800, lastUpated: new Date('2025-12-20') },
    { id: 2, primaryItemCategory: 'beer', secondaryItemCategory: 'pilsner', name: 'Tuborg Classic', averagePrice: 15, currentStock: 95, totalStockValue: 1425, lastUpated: new Date('2025-12-21') },
    { id: 3, primaryItemCategory: 'beer', secondaryItemCategory: 'ipa', name: 'Mikkeller IPA', averagePrice: 25, currentStock: 48, totalStockValue: 1200, lastUpated: new Date('2025-12-22') },
    { id: 4, primaryItemCategory: 'beer', secondaryItemCategory: 'lager', name: 'Brooklyn Lager', averagePrice: 22, currentStock: 64, totalStockValue: 1408, lastUpated: new Date('2025-12-23') },
    { id: 5, primaryItemCategory: 'beer', secondaryItemCategory: 'pilsner', name: 'Royal Unibrew', averagePrice: 18, currentStock: 88, totalStockValue: 1584, lastUpated: new Date('2025-12-24') },
    { id: 6, primaryItemCategory: 'beer', secondaryItemCategory: 'stout', name: 'Guinness Stout', averagePrice: 28, currentStock: 72, totalStockValue: 2016, lastUpated: new Date('2025-12-25') },
    { id: 7, primaryItemCategory: 'cider', secondaryItemCategory: 'apple cider', name: 'Somersby Apple', averagePrice: 20, currentStock: 110, totalStockValue: 2200, lastUpated: new Date('2025-12-20') },
    { id: 8, primaryItemCategory: 'cider', secondaryItemCategory: 'perry', name: 'Sommersby Pear', averagePrice: 20, currentStock: 85, totalStockValue: 1700, lastUpated: new Date('2025-12-21') },
    { id: 9, primaryItemCategory: 'cider', secondaryItemCategory: 'dry cider', name: 'Strongbow Original', averagePrice: 22, currentStock: 92, totalStockValue: 2024, lastUpated: new Date('2025-12-22') },
    { id: 10, primaryItemCategory: 'cider', secondaryItemCategory: 'fruit cider', name: 'Rekorderlig Strawberry', averagePrice: 25, currentStock: 67, totalStockValue: 1675, lastUpated: new Date('2025-12-23') },
    { id: 11, primaryItemCategory: 'wine', secondaryItemCategory: 'red', name: 'Chianti Classico', averagePrice: 45, currentStock: 36, totalStockValue: 1620, lastUpated: new Date('2025-12-24') },
    { id: 12, primaryItemCategory: 'wine', secondaryItemCategory: 'white', name: 'Pinot Grigio', averagePrice: 35, currentStock: 42, totalStockValue: 1470, lastUpated: new Date('2025-12-25') },
    { id: 13, primaryItemCategory: 'wine', secondaryItemCategory: 'white', name: 'Sauvignon Blanc', averagePrice: 38, currentStock: 38, totalStockValue: 1444, lastUpated: new Date('2025-12-26') },
    { id: 14, primaryItemCategory: 'wine', secondaryItemCategory: 'red', name: 'Merlot Reserve', averagePrice: 42, currentStock: 29, totalStockValue: 1218, lastUpated: new Date('2025-12-27') },
    { id: 15, primaryItemCategory: 'wine', secondaryItemCategory: 'sparkling', name: 'Prosecco', averagePrice: 40, currentStock: 55, totalStockValue: 2200, lastUpated: new Date('2025-12-20') },
    { id: 16, primaryItemCategory: 'wine', secondaryItemCategory: 'rosé', name: 'Rosé Provence', averagePrice: 48, currentStock: 31, totalStockValue: 1488, lastUpated: new Date('2025-12-21') },
    { id: 17, primaryItemCategory: 'spirit', secondaryItemCategory: 'whiskey', name: 'Jameson Irish Whiskey', averagePrice: 65, currentStock: 24, totalStockValue: 1560, lastUpated: new Date('2025-12-22') },
    { id: 18, primaryItemCategory: 'spirit', secondaryItemCategory: 'gin', name: 'Tanqueray Gin', averagePrice: 55, currentStock: 32, totalStockValue: 1760, lastUpated: new Date('2025-12-23') },
    { id: 19, primaryItemCategory: 'spirit', secondaryItemCategory: 'vodka', name: 'Absolut Vodka', averagePrice: 60, currentStock: 28, totalStockValue: 1680, lastUpated: new Date('2025-12-24') },
    { id: 20, primaryItemCategory: 'spirit', secondaryItemCategory: 'rum', name: 'Bacardi White Rum', averagePrice: 50, currentStock: 35, totalStockValue: 1750, lastUpated: new Date('2025-12-25') },
    { id: 21, primaryItemCategory: 'soda', secondaryItemCategory: 'coca cola', name: 'Coca-Cola', averagePrice: 12, currentStock: 200, totalStockValue: 2400, lastUpated: new Date('2025-12-26') },
    { id: 22, primaryItemCategory: 'soda', secondaryItemCategory: 'fanta orange', name: 'Fanta Orange', averagePrice: 12, currentStock: 180, totalStockValue: 2160, lastUpated: new Date('2025-12-27') },
    { id: 23, primaryItemCategory: 'soda', secondaryItemCategory: 'other', name: 'Sprite', averagePrice: 12, currentStock: 165, totalStockValue: 1980, lastUpated: new Date('2025-12-20') },
    { id: 24, primaryItemCategory: 'other', secondaryItemCategory: 'sparkling water', name: 'Sparkling Water', averagePrice: 10, currentStock: 150, totalStockValue: 1500, lastUpated: new Date('2025-12-21') },
    { id: 25, primaryItemCategory: 'other', secondaryItemCategory: 'still water', name: 'Still Water', averagePrice: 8, currentStock: 175, totalStockValue: 1400, lastUpated: new Date('2025-12-22') },

    // Additional Beer Types
    { id: 26, primaryItemCategory: 'beer', secondaryItemCategory: 'amber ale', name: 'Amber Ale', averagePrice: 24, currentStock: 45, totalStockValue: 1080, lastUpated: new Date('2025-12-23') },
    { id: 27, primaryItemCategory: 'beer', secondaryItemCategory: 'american ipa', name: 'American IPA', averagePrice: 26, currentStock: 52, totalStockValue: 1352, lastUpated: new Date('2025-12-24') },
    { id: 28, primaryItemCategory: 'beer', secondaryItemCategory: 'barleywine', name: 'Barleywine', averagePrice: 35, currentStock: 28, totalStockValue: 980, lastUpated: new Date('2025-12-25') },
    { id: 29, primaryItemCategory: 'beer', secondaryItemCategory: 'belgian ale', name: 'Belgian Ale', averagePrice: 30, currentStock: 38, totalStockValue: 1140, lastUpated: new Date('2025-12-26') },
    { id: 30, primaryItemCategory: 'beer', secondaryItemCategory: 'belgian ipa', name: 'Belgian IPA', averagePrice: 28, currentStock: 41, totalStockValue: 1148, lastUpated: new Date('2025-12-27') },
    { id: 31, primaryItemCategory: 'beer', secondaryItemCategory: 'black ipa', name: 'Black IPA', averagePrice: 27, currentStock: 33, totalStockValue: 891, lastUpated: new Date('2025-12-28') },
    { id: 32, primaryItemCategory: 'beer', secondaryItemCategory: 'bock', name: 'Bock Beer', averagePrice: 23, currentStock: 47, totalStockValue: 1081, lastUpated: new Date('2025-12-29') },
    { id: 33, primaryItemCategory: 'beer', secondaryItemCategory: 'brown ale', name: 'Brown Ale', averagePrice: 22, currentStock: 55, totalStockValue: 1210, lastUpated: new Date('2025-12-30') },
    { id: 34, primaryItemCategory: 'beer', secondaryItemCategory: 'cream ale', name: 'Cream Ale', averagePrice: 20, currentStock: 60, totalStockValue: 1200, lastUpated: new Date('2025-12-31') },
    { id: 35, primaryItemCategory: 'beer', secondaryItemCategory: 'double ipa', name: 'Double IPA', averagePrice: 32, currentStock: 36, totalStockValue: 1152, lastUpated: new Date('2026-01-01') },
    { id: 36, primaryItemCategory: 'beer', secondaryItemCategory: 'east coast ipa', name: 'East Coast IPA', averagePrice: 27, currentStock: 44, totalStockValue: 1188, lastUpated: new Date('2026-01-02') },
    { id: 37, primaryItemCategory: 'beer', secondaryItemCategory: 'english ipa', name: 'English IPA', averagePrice: 26, currentStock: 39, totalStockValue: 1014, lastUpated: new Date('2025-12-23') },
    { id: 38, primaryItemCategory: 'beer', secondaryItemCategory: 'hazy ipa', name: 'Hazy IPA', averagePrice: 29, currentStock: 51, totalStockValue: 1479, lastUpated: new Date('2025-12-24') },
    { id: 39, primaryItemCategory: 'beer', secondaryItemCategory: 'hefeweizen', name: 'Hefeweizen', averagePrice: 24, currentStock: 46, totalStockValue: 1104, lastUpated: new Date('2025-12-25') },
    { id: 40, primaryItemCategory: 'beer', secondaryItemCategory: 'imperial ipa', name: 'Imperial IPA', averagePrice: 34, currentStock: 29, totalStockValue: 986, lastUpated: new Date('2025-12-26') },
    { id: 41, primaryItemCategory: 'beer', secondaryItemCategory: 'kolsch', name: 'Kölsch', averagePrice: 21, currentStock: 58, totalStockValue: 1218, lastUpated: new Date('2025-12-27') },
    { id: 42, primaryItemCategory: 'beer', secondaryItemCategory: 'milkshake ipa', name: 'Milkshake IPA', averagePrice: 30, currentStock: 35, totalStockValue: 1050, lastUpated: new Date('2025-12-28') },
    { id: 43, primaryItemCategory: 'beer', secondaryItemCategory: 'new england ipa', name: 'New England IPA', averagePrice: 31, currentStock: 42, totalStockValue: 1302, lastUpated: new Date('2025-12-29') },
    { id: 44, primaryItemCategory: 'beer', secondaryItemCategory: 'pale ale', name: 'Pale Ale', averagePrice: 23, currentStock: 63, totalStockValue: 1449, lastUpated: new Date('2025-12-30') },
    { id: 45, primaryItemCategory: 'beer', secondaryItemCategory: 'porter', name: 'Porter', averagePrice: 25, currentStock: 49, totalStockValue: 1225, lastUpated: new Date('2025-12-31') },
    { id: 46, primaryItemCategory: 'beer', secondaryItemCategory: 'red ale', name: 'Red Ale', averagePrice: 24, currentStock: 54, totalStockValue: 1296, lastUpated: new Date('2026-01-01') },
    { id: 47, primaryItemCategory: 'beer', secondaryItemCategory: 'saison', name: 'Saison', averagePrice: 27, currentStock: 37, totalStockValue: 999, lastUpated: new Date('2026-01-02') },
    { id: 48, primaryItemCategory: 'beer', secondaryItemCategory: 'session ipa', name: 'Session IPA', averagePrice: 22, currentStock: 68, totalStockValue: 1496, lastUpated: new Date('2025-12-23') },
    { id: 49, primaryItemCategory: 'beer', secondaryItemCategory: 'sour', name: 'Sour Beer', averagePrice: 28, currentStock: 31, totalStockValue: 868, lastUpated: new Date('2025-12-24') },
    { id: 50, primaryItemCategory: 'beer', secondaryItemCategory: 'triple ipa', name: 'Triple IPA', averagePrice: 36, currentStock: 24, totalStockValue: 864, lastUpated: new Date('2025-12-25') },
    { id: 51, primaryItemCategory: 'beer', secondaryItemCategory: 'west coast ipa', name: 'West Coast IPA', averagePrice: 28, currentStock: 48, totalStockValue: 1344, lastUpated: new Date('2025-12-26') },
    { id: 52, primaryItemCategory: 'beer', secondaryItemCategory: 'wheat beer', name: 'Wheat Beer', averagePrice: 22, currentStock: 57, totalStockValue: 1254, lastUpated: new Date('2025-12-27') },
    { id: 53, primaryItemCategory: 'beer', secondaryItemCategory: 'white ipa', name: 'White IPA', averagePrice: 26, currentStock: 43, totalStockValue: 1118, lastUpated: new Date('2025-12-28') },

    // Additional Cider Types
    { id: 54, primaryItemCategory: 'cider', secondaryItemCategory: 'berry cider', name: 'Berry Cider', averagePrice: 23, currentStock: 74, totalStockValue: 1702, lastUpated: new Date('2025-12-29') },
    { id: 55, primaryItemCategory: 'cider', secondaryItemCategory: 'hard cider', name: 'Hard Cider', averagePrice: 24, currentStock: 68, totalStockValue: 1632, lastUpated: new Date('2025-12-30') },
    { id: 56, primaryItemCategory: 'cider', secondaryItemCategory: 'hopped cider', name: 'Hopped Cider', averagePrice: 26, currentStock: 52, totalStockValue: 1352, lastUpated: new Date('2025-12-31') },
    { id: 57, primaryItemCategory: 'cider', secondaryItemCategory: 'ice cider', name: 'Ice Cider', averagePrice: 35, currentStock: 28, totalStockValue: 980, lastUpated: new Date('2026-01-01') },
    { id: 58, primaryItemCategory: 'cider', secondaryItemCategory: 'rosé cider', name: 'Rosé Cider', averagePrice: 25, currentStock: 61, totalStockValue: 1525, lastUpated: new Date('2026-01-02') },
    { id: 59, primaryItemCategory: 'cider', secondaryItemCategory: 'scrumpy', name: 'Scrumpy', averagePrice: 21, currentStock: 48, totalStockValue: 1008, lastUpated: new Date('2025-12-23') },
    { id: 60, primaryItemCategory: 'cider', secondaryItemCategory: 'semi-dry cider', name: 'Semi-Dry Cider', averagePrice: 22, currentStock: 70, totalStockValue: 1540, lastUpated: new Date('2025-12-24') },
    { id: 61, primaryItemCategory: 'cider', secondaryItemCategory: 'semi-sweet cider', name: 'Semi-Sweet Cider', averagePrice: 23, currentStock: 65, totalStockValue: 1495, lastUpated: new Date('2025-12-25') },
    { id: 62, primaryItemCategory: 'cider', secondaryItemCategory: 'sweet cider', name: 'Sweet Cider', averagePrice: 24, currentStock: 72, totalStockValue: 1728, lastUpated: new Date('2025-12-26') },

    // Additional Wine Types
    { id: 63, primaryItemCategory: 'wine', secondaryItemCategory: 'champagne', name: 'Champagne Brut', averagePrice: 85, currentStock: 22, totalStockValue: 1870, lastUpated: new Date('2025-12-27') },
    { id: 64, primaryItemCategory: 'wine', secondaryItemCategory: 'orange', name: 'Orange Wine', averagePrice: 52, currentStock: 18, totalStockValue: 936, lastUpated: new Date('2025-12-28') },
    { id: 65, primaryItemCategory: 'wine', secondaryItemCategory: 'portwine', name: 'Port Wine', averagePrice: 68, currentStock: 26, totalStockValue: 1768, lastUpated: new Date('2025-12-29') },

    // Additional Spirit Types
    { id: 66, primaryItemCategory: 'spirit', secondaryItemCategory: 'absinthe', name: 'Absinthe', averagePrice: 75, currentStock: 12, totalStockValue: 900, lastUpated: new Date('2025-12-30') },
    { id: 67, primaryItemCategory: 'spirit', secondaryItemCategory: 'bourbon', name: 'Bourbon Whiskey', averagePrice: 70, currentStock: 20, totalStockValue: 1400, lastUpated: new Date('2025-12-31') },
    { id: 68, primaryItemCategory: 'spirit', secondaryItemCategory: 'brandy', name: 'Brandy', averagePrice: 58, currentStock: 25, totalStockValue: 1450, lastUpated: new Date('2026-01-01') },
    { id: 69, primaryItemCategory: 'spirit', secondaryItemCategory: 'cognac', name: 'Cognac', averagePrice: 95, currentStock: 15, totalStockValue: 1425, lastUpated: new Date('2026-01-02') },
    { id: 70, primaryItemCategory: 'spirit', secondaryItemCategory: 'irish whiskey', name: 'Irish Whiskey Premium', averagePrice: 72, currentStock: 18, totalStockValue: 1296, lastUpated: new Date('2025-12-23') },
    { id: 71, primaryItemCategory: 'spirit', secondaryItemCategory: 'liqueur', name: 'Liqueur', averagePrice: 42, currentStock: 34, totalStockValue: 1428, lastUpated: new Date('2025-12-24') },
    { id: 72, primaryItemCategory: 'spirit', secondaryItemCategory: 'mezcal', name: 'Mezcal', averagePrice: 68, currentStock: 16, totalStockValue: 1088, lastUpated: new Date('2025-12-25') },
    { id: 73, primaryItemCategory: 'spirit', secondaryItemCategory: 'rye whiskey', name: 'Rye Whiskey', averagePrice: 66, currentStock: 21, totalStockValue: 1386, lastUpated: new Date('2025-12-26') },
    { id: 74, primaryItemCategory: 'spirit', secondaryItemCategory: 'schnapps', name: 'Schnapps', averagePrice: 38, currentStock: 42, totalStockValue: 1596, lastUpated: new Date('2025-12-27') },
    { id: 75, primaryItemCategory: 'spirit', secondaryItemCategory: 'scotch', name: 'Scotch Whisky', averagePrice: 78, currentStock: 19, totalStockValue: 1482, lastUpated: new Date('2025-12-28') },
    { id: 76, primaryItemCategory: 'spirit', secondaryItemCategory: 'tequila', name: 'Tequila Reposado', averagePrice: 62, currentStock: 27, totalStockValue: 1674, lastUpated: new Date('2025-12-29') },

    // Additional Soda Types
    { id: 77, primaryItemCategory: 'soda', secondaryItemCategory: 'coca cola zero', name: 'Coca-Cola Zero', averagePrice: 12, currentStock: 190, totalStockValue: 2280, lastUpated: new Date('2025-12-30') },
    { id: 78, primaryItemCategory: 'soda', secondaryItemCategory: 'faxe kondi', name: 'Faxe Kondi', averagePrice: 13, currentStock: 140, totalStockValue: 1820, lastUpated: new Date('2025-12-31') },
    { id: 79, primaryItemCategory: 'soda', secondaryItemCategory: 'pepsi', name: 'Pepsi', averagePrice: 12, currentStock: 185, totalStockValue: 2220, lastUpated: new Date('2026-01-01') },
    { id: 80, primaryItemCategory: 'soda', secondaryItemCategory: 'pepsi max', name: 'Pepsi Max', averagePrice: 12, currentStock: 175, totalStockValue: 2100, lastUpated: new Date('2026-01-02') },
    { id: 81, primaryItemCategory: 'soda', secondaryItemCategory: 'sweppes lemon', name: 'Schweppes Lemon', averagePrice: 13, currentStock: 125, totalStockValue: 1625, lastUpated: new Date('2025-12-23') },
];

export const mockUsers: User[] = [
    {
        id: '0001',
        name: 'Jonas Madvig',
        email: 'jonas.e.madvig@gmail.com',
        role: 'sudo-admin',
        balance: 300.00,
        valuta: 'DKK',
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2025-12-28'),
    },
    {
        id: '0002',
        name: 'Bob Builder',
        email: 'bob@example.com',
        role: 'user',
        balance: 45.00,
        valuta: 'DKK',
        createdAt: new Date('2024-03-20'),
        updatedAt: new Date('2025-12-29'),
    },
    {
        id: '0003',
        name: 'Charlie Chen',
        email: 'charlie@example.com',
        role: 'sudo-admin',
        balance: 0.00,
        valuta: 'DKK',
        createdAt: new Date('2023-11-10'),
        updatedAt: new Date('2025-12-29'),
    },
    {
        id: '0004',
        name: 'Diana Davis',
        email: 'diana@example.com',
        role: 'user',
        balance: -320.75,
        valuta: 'DKK',
        createdAt: new Date('2024-06-05'),
        updatedAt: new Date('2025-12-27'),
    },
    {
        id: '0005',
        name: 'Eric Evans',
        email: 'eric@example.com',
        role: 'user',
        balance: -12.25,
        valuta: 'DKK',
        createdAt: new Date('2024-08-14'),
        updatedAt: new Date('2025-12-29'),
    },
];
